Assets/02.Scripts/SaveManager.cs
- SaveManager를 싱글톤 패턴에서 static 함수들로 수정하여 오브젝트가 존재하지 않더라도 사용할 수 있도록 변경 
- SaveManager가 싱글톤이 아니게 되었기 때문에 기존에 고려했던 예외처리를 없애고 데이터를 읽어오도록 구현
=> SaveManager를 통해 세이브 데이터를 읽어오도록 수정

Assets/02.Scripts/HamsterFunction/Hamster.cs
=> 햄스터 구조 변경및 합침으로 인한 오류 수정

Assets/01.Scenes/WalkScene.unity, Assets/02.Scripts/Data/Database.cs, Assets/02.Scripts/Walking/ChestCount.cs, Assets/02.Scripts/Walking/Map/DistanceCalculator.cs, Assets/02.Scripts/Walking/Map/DistanceCalculator.cs.meta, Assets/02.Scripts/Walking/Map/GPS.cs, Assets/02.Scripts/Walking/Map/GoogleMapInterface.cs, Assets/02.Scripts/Walking/Map/Minimap.cs
map api key를 gitignore로 올리기
map스크립트 최적화를 위한 계산 스크립트
코인 상자 수를 위한 스크립트.
=> gps 최적화를 위한 계산 스크립트, 코인 상자 수를 위한 스크립트

Assets/01.Scenes/LinkHamsterTravel.unity, Assets/01.Scenes/LinkHamsterTravel.unity.meta, Assets/02.Scripts/HamsterFunction/Hamster.cs, Assets/02.Scripts/Travel/Travel.cs, Assets/03.Assets/Hamster.prefab, Assets/05.Prefabs/Travel/TravelPanel.prefab
=> 햄스터와 여행 연결

Assets/01.Scenes/SouvenirPopup.unity, Assets/01.Scenes/SouvenirPopup.unity.meta, Assets/02.Scripts/Souvenir/SouvenirManager.cs, Assets/05.Prefabs/Travel/SouvenirPopup.prefab, Assets/05.Prefabs/Travel/SouvenirPopup.prefab.meta
=> 햄스터가 여행에서 돌아오면 팝업을 띄움

Assets/02.Scripts/Walking/ChestCount.cs
코인 추가시 코인 저장하도록 스크립트 수정
_inventoryData 추가.
ChestOpen 함수에 Save(_inventoryData) 추가
=> 코인상자 버튼 클릭시 코인 저장

Assets/01.Scenes/HamStar.unity
팝업이 사라지지 않는 문제 해결
기념품 획득 테스트용 버튼 제거
=> 팝업이 사라지지 않는 문제 해결

Assets/02.Scripts/HamsterFunction/Hamster.cs
=> 상호작용과 스텟 연결하기

Assets/02.Scripts/Souvenir/SouvenirManager.cs
https://github.com/ETL11-CodeCraft/HamStar/issues/84
=> 기념품 패널의 이동버튼이 정상적으로 작동하지 않는 문제 수정

Assets/02.Scripts/HamsterWheel/HamsterWheel.cs, Assets/03.Assets/HamsterWheel.prefab
쳇바퀴 프리팹에서 RigidBody 삭제
https://github.com/ETL11-CodeCraft/HamStar/issues/86
=> 햄스터가 쳇바퀴에 올라타지 못하고 쳇바퀴를 통과해 바닥에 닿는 현상 수정

Assets/02.Scripts/Data/Database.cs, Assets/02.Scripts/Shop/controller/ShopController.cs, Assets/02.Scripts/Shop/data/Product.cs, Assets/07.ScriptableObjects/Shop/Product_01_BasicFood.asset, Assets/07.ScriptableObjects/Shop/Product_02_SpecialFood.asset, Assets/07.ScriptableObjects/Shop/Product_03_Medicine.asset, Assets/07.ScriptableObjects/Shop/Product_04_HamsterWheel.asset, Assets/07.ScriptableObjects/Shop/Shop Data.asset
상품 SO에 수량 정보 저장하지 않도록 수정,
PlayGround 타입 상품의 경우 이미 보유하고 있을 경우 상점에서 구매 불가 처리
https://github.com/ETL11-CodeCraft/HamStar/issues/88
=> 쳇바퀴 여러 개 구매할 수 있는 현상 수정

Assets/01.Scenes/HamStar.unity, Assets/02.Scripts/GameManager.cs, Assets/02.Scripts/HamsterFunction/Hamster.cs, Assets/02.Scripts/HamsterFunction/LoveManager.cs, Assets/02.Scripts/Shop/controller/ProductController.cs, Assets/02.Scripts/Shop/controller/ShopController.cs, Assets/02.Scripts/ShopTest/ShopTest.cs, Assets/02.Scripts/Souvenir/SouvenirManager.cs, Assets/02.Scripts/Walking/ChestCount.cs, Assets/05.Prefabs/HamsterStat/Cleanliness.prefab, Assets/05.Prefabs/HamsterStat/Closeness.prefab, Assets/05.Prefabs/HamsterStat/Fullness.prefab, Assets/05.Prefabs/HamsterStat/Stress.prefab
터치로 햄스터 웰빙상태 조절할 수 있었던 문제 해결
애정주기 상태에서는 스와이프 하지않기 및 슬라이드가 가득차면 애정 30 추가
GameManager 싱글톤으로 변경
상점 UI가 열린상태에서 좌우 스와이프가 가능한 문제 해결
https://github.com/ETL11-CodeCraft/HamStar/issues/81
=> 상점 UI가 열린상태에서 좌우 스와이프가 가능한 문제 해결

Assets/02.Scripts/HamsterFunction/Hamster.cs, Assets/02.Scripts/HamsterWheel/HamsterWheel.cs
햄스터가 쳇바퀴에서 내리면 실행되는 함수 추가
https://github.com/ETL11-CodeCraft/HamStar/issues/99
=> 햄스터가 쳇바퀴에서 내리면 실행되는 함수 추가

Assets/01.Scenes/HamStar.unity, Assets/02.Scripts/Souvenir/SouvenirInfo.cs
기념품 설명 글자크기 키우기
https://github.com/ETL11-CodeCraft/HamStar/issues/102 기념품 상세 켜져있을때 버튼 클릭 안되게 하기
기념품 상세 켜져있을때 스와이프 안되게 하기
=> 기념품 상세 켜져있을때 버튼 클릭 안되게 하기

Assets/02.Scripts/HamsterWheel/HamsterWheel.cs
쓰이지 않는 함수 삭제 (RunWheel, StopWheel)
ActivateWheel, DeactiveWheel 호출 시에 애니메이터 변경하도록 수정함
#101
=> 햄스터가 타면 쳇바퀴 애니메이션

Assets/01.Scenes/HamStar.unity
=> Walk UI 씬 병합

Assets/01.Scenes/HamStar.unity, Assets/02.Scripts/HamsterFunction/Hamster.cs
https://github.com/ETL11-CodeCraft/HamStar/issues/82 햄스터가 떨어지면 카메라 위치에 오도록 조정
수직평면은 인식하지 않도록 변경
=> 햄스터가 떨어지는 문제 수정

Assets/02.Scripts/HamsterFunction/Hamster.cs, Assets/02.Scripts/HamsterFunction/LoveManager.cs
https://github.com/ETL11-CodeCraft/HamStar/issues/110 햄스터가 애정주기 상태에서 움직이지 않도록 수정
=> 햄스터가 애정주기 상태에서 움직이지 않도록 수정

Assets/01.Scenes/HamStar.unity, Assets/05.Prefabs/HamsterStat/Cleanliness.prefab, Assets/05.Prefabs/HamsterStat/Closeness.prefab, Assets/05.Prefabs/HamsterStat/DarkenMarkBG.prefab, Assets/05.Prefabs/HamsterStat/Fullness.prefab, Assets/05.Prefabs/HamsterStat/Stress.prefab
https://github.com/ETL11-CodeCraft/HamStar/issues/108 UI 겹침현상 수정
기념품 글자 크기 수정
=> UI 겹침 현상 수정

Assets/02.Scripts/HamsterFunction/Hamster.cs, Assets/02.Scripts/ObjectController.meta, Assets/02.Scripts/ObjectController/Poop.cs, Assets/02.Scripts/ObjectController/Poop.cs.meta, Assets/02.Scripts/ObjectController/Seed.cs, Assets/02.Scripts/ObjectController/Seed.cs.meta, Assets/03.Assets/Hamster.prefab, Assets/03.Assets/SunFlowerSeed -gold.prefab, Assets/03.Assets/SunFlowerSeed.prefab, Assets/05.Prefabs/Poop/TempPoop.prefab
https://github.com/ETL11-CodeCraft/HamStar/issues/118 씨앗과 똥이 떨어지면 사라지도록 수정
=> 씨앗과 똥이 떨어지면 사라지도록 수정

Assets/01.Scenes/HamStar.unity, Assets/02.Scripts/Souvenir/Souvenir.cs
=> 기념품 관련 버튼 사운드 추가

Assets/01.Scenes/HamStar.unity
UI 수정및 Travel상황에서 Swipe안되는 오류 수정
=> UI 수정및 Travel상황에서 Swipe안되는 오류 수정

Assets/01.Scenes/HamStar.unity, ProjectSettings/EditorBuildSettings.asset
https://github.com/ETL11-CodeCraft/HamStar/issues/123 설정 패널 ui 크기 조절
=> 설정 패널 ui 크기 조절

Assets/02.Scripts/HamsterFunction/Hamster.cs, Assets/03.Assets/Hamster.prefab
인풋액션 참조 Mouse Click -> Touch Tap
#130
=> 햄스터 응가 터치 안 되는 문제 수정

Assets/02.Scripts/HamsterFunction/Hamster.cs, Assets/02.Scripts/Travel/Travel.cs
https://github.com/ETL11-CodeCraft/HamStar/issues/132 여행 중 흑화상태가 되는 문제 및 흑화상태로 접속했을때 여행 중일 시간이라면 여행을 가는 문제 해결
=> 여행 중 흑화상태가 되는 문제 및 흑화상태로 접속했을때 여행 중일 시간이라면 여행을 가는 문제 해결

Assets/02.Scripts/HamsterFunction/Hamster.cs
https://github.com/ETL11-CodeCraft/HamStar/issues/135 여행을 갔다면 흑화 아이콘이 보이는 문제 해결
=> 여행을 갔다면 흑화 아이콘이 보이는 문제 해결

Assets/01.Scenes/HamStar.unity, Assets/02.Scripts/GameManager.cs, Assets/02.Scripts/HamsterFunction/FeedingManager.cs, Assets/02.Scripts/HamsterFunction/Hamster.cs, Assets/02.Scripts/HamsterFunction/PotionManager.cs, Assets/02.Scripts/Shop/AR/HamsterWheelPlacementController.cs
먹이 개수가 0일 때 먹이주기 가능한 문제 및 똥 줍기 다시 안 되는 문제 수정
#138
=> 먹이 개수가 0일 때 먹이주기 가능한 문제 및 똥 청소 다시 안 되는 문제 수정

Assets/02.Scripts/GameManager.cs, Assets/02.Scripts/Shop/AR/HamsterWheelPlacementController.cs
=> 쳇바퀴 구매시 GameManager의 Wheel 값 설정

Assets/02.Scripts/HamsterFunction/Hamster.cs
=> 스트레스 값 초기화가 정상적으로 되지 않던 문제 수정
